# Generated by Django 5.2.3 on 2025-06-12 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeuModelo',
            new_name='MeusIds',
        ),
    ]
