# Generated by Django 5.2.3 on 2025-06-12 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_meumodelo_meusids'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeusIds',
            new_name='Id',
        ),
    ]
