# Generated by Django 5.2.3 on 2025-06-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_rename_meusids_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Id',
            new_name='Id_cliente',
        ),
    ]
