# Generated by Django 5.2.3 on 2025-06-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_nome_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='cpf_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14)),
            ],
        ),
        migrations.DeleteModel(
            name='Id_cliente',
        ),
    ]
