# Generated by Django 5.2.3 on 2025-06-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cliente_delete_cpf_cliente_delete_nome_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(default='00000-000', max_length=9),
        ),
    ]
