# Generated by Django 5.2.3 on 2025-06-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_remove_cliente_id_alter_cliente_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cep',
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(default='Sem endereço', max_length=200),
        ),
    ]
