# Generated by Django 5.2.3 on 2025-06-26 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_remove_cliente_cep_cliente_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_funcionario', models.CharField(max_length=100)),
                ('cargo_funcionario', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade_item', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nome_materia', models.CharField(max_length=100)),
                ('descricao_materia', models.CharField(max_length=200)),
                ('estoque_materia', models.IntegerField()),
                ('medida_materia', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=45)),
                ('descricao_produto', models.CharField(max_length=200)),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque_produto', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(default='00000-000', max_length=9),
        ),
        migrations.CreateModel(
            name='FuncionarioHasItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.funcionario')),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.itempedido')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('data_pedido', models.DateTimeField()),
                ('status_pedido', models.CharField(max_length=45)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.pedido'),
        ),
        migrations.CreateModel(
            name='OrdemDeProducao',
            fields=[
                ('id_ordem', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('quantidade_produzida', models.IntegerField()),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.funcionario')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.produto')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaPrimaHasProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.materiaprima')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.produto')),
            ],
        ),
        migrations.AddField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.produto'),
        ),
        migrations.CreateModel(
            name='FuncionarioHasProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.funcionario')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoHasOrdemDeProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.ordemdeproducao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.produto')),
            ],
        ),
    ]
