# Generated by Django 5.2.3 on 2025-06-26 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_funcionario_itempedido_materiaprima_produto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionariohasproduto',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='funcionariohasproduto',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='materiaprimahasproduto',
            name='materia_prima',
        ),
        migrations.RemoveField(
            model_name='materiaprimahasproduto',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='produtohasordemdeproducao',
            name='ordem_producao',
        ),
        migrations.RemoveField(
            model_name='produtohasordemdeproducao',
            name='produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='funcionarios',
            field=models.ManyToManyField(related_name='produtos', to='clientes.funcionario'),
        ),
        migrations.AddField(
            model_name='produto',
            name='materias_primas',
            field=models.ManyToManyField(related_name='produtos', to='clientes.materiaprima'),
        ),
        migrations.CreateModel(
            name='FuncionarioTemItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acao', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.funcionario')),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.itempedido')),
            ],
        ),
        migrations.DeleteModel(
            name='FuncionarioHasItemPedido',
        ),
        migrations.DeleteModel(
            name='FuncionarioHasProduto',
        ),
        migrations.DeleteModel(
            name='MateriaPrimaHasProduto',
        ),
        migrations.DeleteModel(
            name='ProdutoHasOrdemDeProducao',
        ),
    ]
